# Fase de construcción (build)
FROM maven:3.8.7-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Fase de ejecución
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/padel-*.jar /app/padel.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "padel.jar", "--spring.profiles.active=prod"]