spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # ¡Nunca usar 'update' en producción!
    show-sql: false
logging:
  file:
    name: /var/log/padel/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  level:
    root: WARN		
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: tomcat