spring:
  datasource:
    url: jdbc:mysql://localhost:3306/padel_db?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.laspalmeras.padel: DEBUG