name: Generar Documentación

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generar-documentacion:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener Repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          server-id: github
          cache: maven
          
      - name: Construir Proyecto y Generar Documentación
        run: mvn clean install site
        
      - name: Verificar Archivos Generados
        run: ls -l ./target/site/

      - name: Verificar `apidocs` Generados
        run: ls -l ./target/site/apidocs/

      - name: Desplegar Documentación
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          publish_branch: gh-pages
