name: Generar Documentación

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generar-documentacion:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener Repositorio
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD

      - name: Compilar con Maven
        run: mvn clean package

      - name: Generar Javadoc
        run: mvn javadoc:javadoc

      - name: Desplegar Documentación
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
